### ISSUE TITLE
Error when I start atomiadns-webapp in Ubuntu

### ISSUE THREAD

**Issue by bindmisson** [atomia/atomiadns#16]
Hello,

I'm doing installation of atomiadns and atomiadns-webapp.

I followed Following Doc to install

http://atomiadns.com/get-started/install-atomia-dns/

I can't start atomiadns-webapp

It shows starting!

But , When I Check with netstat -tunlp , it is stopped

I'm attatching the Error Log!

AnyOne Can Help me ?

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: undefined is not a function
    at /usr/lib/atomiadns/webapp/node_modules/express/lib/utils.js:38:10
    at Object.<anonymous> (/usr/lib/atomiadns/webapp/node_modules/express/lib/application.js:452:11)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:32)
    at Function._load (module.js:308:12)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/usr/lib/atomiadns/webapp/node_modules/express/lib/express.js:7:13)
    at Module._compile (module.js:441:26)

Waiting for a Solution, Thanks

**Comment by medivhx** [comment]
Hi,

I just had the same problem and debugged - this occurs cause Atomia's webapp installs a version of the Node.js "express" module which is too new apparently.

I'm running on Ubuntu 12.04 here and it comes with node.js 0.6.x - the express module version that Atomia installs for the webapp requires node.js 0.8.x though.

The best way I found to fix this is to downgrade the express module which I did like this:

aptitude update
aptitude -y install npm
cd /usr/lib/atomiadns/webapp/node_modules/
mv express express.backup
npm install express@3.2.2

(3.2.2 seems to be the latest version that supports node.js 0.6.x).

After that, the webapp went back to working fine. Hope this helps! :-)

@Atomia: Would be nice if the dependencies in the webapp package could be fixed accordingly, probably in package.json if I understood correctly - I'm not exactly a Node.js developer and spent an hour trying to get my webapp back online, but finally found the way. :-) Thank you, and keep up the great work, guys!

Cheers,
Chris

Edit: I just came across two other errors which are caused by a too new version of the jade and request modules, to fix do this, after the commands above:

cd /usr/lib/atomiadns/webapp/node_modules/
mv jade jade.backup
mv request request.backup
npm install jade@0.27.7
npm install request@2.9.100
