### ISSUE TITLE
PowerDNS API ??

### ISSUE THREAD

**Issue by rogeriobastos** [atomia/atomiadns#24]
Why do you not use PowerDNS API ?

https://doc.powerdns.com/md/httpapi/README/

**Comment by jimmybergman** [comment]
Several reasons:
1. It is only supported in 3.4 and we supported PowerDNS as a nameserver long before that
2. Even in 3.4 it is marked as experimental
3. The code needed to sync changes to the PowerDNS MySQL schema structure isn't actually that
   complicated - so we have seen no need for considering changing it at this time.

If the HTTP API matures, and time passes so that 3.4+ is the only version that our users run, then maybe in the future we will consider using it instead.
