### ISSUE TITLE
Regexp TXT records 255 character limit

### ISSUE THREAD

**Issue by bennyhansson** [atomia/atomiadns#31]
255 is not enough when you start using stuff like DKIM.

Can we change regexp to: ^"[^"]*"( "[^"]*")*$

**Comment by jimmybergman** [comment]
The current regexp at https://github.com/atomia/atomiadns/blob/develop/server/schema/ddl.sql#L93 

allows not only 255 characters, it allows 255 characters per string and any number of such strings separated by space.

This is the correct restriction, since TXT record strings is defined to only allow 255 characters (but with multiple strings allowed).

More details can be found at https://kb.isc.org/article/AA-00356/0/Can-I-have-a-TXT-or-SPF-record-longer-than-255-characters.html

The fix for DKIM, SPF, etc, is just to take the long TXT records and make cut it at any point to several strings each <= 255 characters.

I.e. like in the example from the ISC article above:
"v=spf1 .... first" "second string..."

instead of
"v=spf1 .... firstsecond string..."
